version: '3.8'
services:
  proxy_nginx: 
    build:
      context: .
      dockerfile: Nginx
    restart: always
    ports:
      - "8888:80"
    container_name: proxy_nginx
    networks:
      proxy_network: 
        ipv4_address: 192.168.1.112

networks:
  proxy_network:
    name: "proxy_network"
    driver: "bridge"
    ipam:
      config:
        - subnet: 192.168.1.0/24
