version: '3.8'
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  backend1:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 9006:9006
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  backend2:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 9007:9006
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  backend3:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 9008:9006
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  backend4:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 9009:9006
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  ## 上面的backend/db 是后端服务用例, 测试Docker in Docker
  proxy_nginx: 
    build:
      context: .
      dockerfile: Nginx
    restart: always
    ports:
      - "8888:80"
    container_name: proxy_nginx
    depends_on: 
      - backend
    networks:
      - frontnet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
